### ISSUE TITLE
if notification payload is number 0, module stuck in loop.

### ISSUE THREAD

**Issue by sdetweil** [tosti007/MMM-TouchNotifications#2]
MMM-Pages wants a notification of 'PAGE_CHANGED', 0

but the code in .js  doesn't correctly check the payload.  null and 0 both are 'false' 
```
buttonClick: function(self, button, notification) {
    if (typeof notification !== "string") {
      if (notification.type && notification.payload) {   < ------
        button.addEventListener("click", function() {
```

**Comment by tosti007** [comment]
Fixed! I simply added a check if its a 0, hope this helps.
If it doesnt let me know.
